name: assist_gui
description: "Assist GUI"
publish_to: 'none'

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  assist_core: ^0.1.0

  meta: ^1.16.0
  path: ^1.9.1
  bloc: ^9.0.0
  go_router: ^15.1.1
  flutter_bloc: ^9.1.0
  shadcn_ui: ^0.24.0
  easy_localization: ^3.0.7+1
  flutter_feather_icons: ^2.0.0+1
  auto_size_text: ^3.0.0
  url_launcher: ^6.3.1
  flutter_breadcrumb: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
