include: package:lints/recommended.yaml

linter:
   rules:
     - prefer_single_quotes
     - always_use_package_imports
     - avoid_relative_lib_imports
     - constant_identifier_names
     - prefer_constructors_over_static_methods
     - use_named_constants
     - prefer_final_locals
     - prefer_final_fields
     - prefer_final_in_for_each
