name: assist_workspace
publish_to: none
workspace:
  - packages/cli
  - packages/core
  - packages/gui

environment:
  sdk: ^3.6.0

# This allows us to use assist during development.
# by running the activate script in melos
executables:
  assist-dev: assist_dev

dependencies:
  chalkdart: ^2.0.9

dev_dependencies:
  melos: ^7.0.0-dev.8

melos:
  ide:
    intellij: true

  scripts:
    pre-commit:
      description: pre-commit git hook script
      steps:
        - format --output none --set-exit-if-changed
        - analyze

    get:
      name: Pub Get
      description: Run pub get on workspace
      run: dart pub get

    analyze:
      name: Analyze Code
      description: Run dart analyze on all packages
      run: melos exec -- dart analyze --fatal-infos

    format:
      name: Format Code
      description: Run dart format on all packages
      run: melos format

    activate:
      description: Activate the local version of assist for development.
      steps:
        - dart pub upgrade
        - rm -rf ./.dart_tool/pub/bin/assist_workspace
        - dart pub global activate --source="path" . --executable="assist-dev"
          --overwrite

    activate:pub:
      description: Activate the published version of assist.
      run: dart pub global activate assist --overwrite

    build:gui:linux:
      name: Build GUI (Linux)
      description: Build a release app bundle for Linux.
      steps:
        - INSTALL_DIR=$HOME/.assist-dev/gui
        - mkdir -p $INSTALL_DIR
        - cd packages/gui
        - flutter build linux --release
        - cp -r build/linux/x64/release/bundle/* $INSTALL_DIR

    build:gui:windows:
      name: Build GUI (Windows)
      description: Build a release app bundle for Windows.
      steps:
        - INSTALL_DIR=$USERPROFILE/.assist-dev/gui
        - mkdir -p $INSTALL_DIR
        - cd packages/gui
        - flutter build windows --release
        - cp -r build/windows/x64/release/bundle/* $INSTALL_DIR

    build:gui:macos:
      name: Build GUI (macOS)
      description: Build a release app bundle for macOS.
      steps:
        - INSTALL_DIR=$HOME/.assist-dev/gui
        - mkdir -p $INSTALL_DIR
        - cd packages/gui
        - flutter build macos --release
        - cp -r build/macos/x64/release/bundle/* $INSTALL_DIR