name: assist_workspace
publish_to: none
workspace:
  - packages/cli
  - packages/core
  - packages/gui

environment:
  sdk: ^3.6.0

# This allows us to use assist during development.
# by running the activate script in melos
executables:
  assist: assist_dev

dependencies:
  chalkdart: ^2.0.9

dev_dependencies:
  melos: ^7.0.0-dev.8

melos:
  ide:
    intellij: true

  scripts:
    pre-commit:
      description: pre-commit git hook script
      steps:
        - format --output none --set-exit-if-changed
        - analyze

    get:
      name: Pub Get
      description: Run pub get on workspace
      run: dart pub get

    analyze:
      name: Analyze Code
      description: Run dart analyze on all packages
      run: melos exec -- dart analyze --fatal-infos

    format:
      name: Format Code
      description: Run dart format on all packages
      run: melos format

    activate:
      description: Activate the local version of assist for development.
      steps:
        - dart pub upgrade
        - rm -rf ./.dart_tool/pub/bin/assist_workspace
        - dart pub global activate --source="path" . --executable="assist"
          --overwrite

    activate:pub:
      description: Activate the published version of assist.
      run: dart pub global activate assist --overwrite