name: Build GUI Release

on:
  push:
    tags:
      - 'assist-v*'          # Trigger only on version tags like v1.2.3
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    defaults:
      run:
        working-directory: packages/gui

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          cache: true

      - name: Enable desktop support
        run: flutter config --enable-${{ matrix.os == 'windows-latest' && 'windows' || matrix.os == 'macos-latest' && 'macos' || 'linux' }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build GUI App
        run: |
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            flutter build windows
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            flutter build macos
          else
            flutter build linux
          fi

      - name: Archive Build
        run: |
          version=${GITHUB_REF#refs/tags/}
          mkdir dist
          if [[ "${{ runner.os }}" == "Windows" ]]; then
            7z a dist/assist_gui-windows-$version.zip build/windows/runner/Release/*
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            ditto -c -k --sequesterRsrc --keepParent build/macos/Build/Products/Release/Assist.app dist/assist_gui-macos-$version.zip
          else
            tar -czf dist/assist_gui-linux-$version.tar.gz -C build/linux/x64/release/bundle .
          fi

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
