name: assist_core
description: "Assist Core"
version: 0.1.0
repository: https://github.com/salah-rashad/assist

environment:
  sdk: ^3.7.2

resolution: workspace

dependencies:
  io: ^1.0.5
  path: ^1.9.1
  meta: ^1.16.0
  hive: ^2.2.3
  crypto: ^3.0.6
  github: ^9.25.0
  pubspec_parse: ^1.5.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
