name: assist_core
description: "Assist Core"
version: 0.3.1
repository: https://github.com/salah-rashad/assist

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  meta:
  io: ^1.0.5
  path: ^1.9.1
  hive: ^2.2.3
  crypto: ^3.0.6
  github: ^9.25.0
  pubspec_parse: ^1.5.0
  pub_semver: ^2.2.0
  uuid: ^4.5.1
  async: ^2.13.0
  collection: ^1.19.1
  equatable: ^2.0.7
  test_report_parser: ^1.2.1

dev_dependencies:
  lints: ^6.0.0
  test:
