name: assist
description: "A tool that helps Dart and Flutter developers save time by automating tasks and making project management easier."
version: 0.2.2
homepage: https://github.com/salah-rashad/assist
repository: https://github.com/salah-rashad/assist
issue_tracker: https://github.com/salah-rashad/assist/issues
documentation: https://github.com/salah-rashad/assist

environment:
  sdk: ^3.7.2

dependencies:
  meta: ^1.16.0
  args: ^2.7.0
  path: ^1.9.1
  promptly: ^1.0.0-alpha.8
  pubspec_parse: ^1.5.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15

executables:
  assist: assist

platforms:
  windows:
  linux:
  macos:

topics:
  - management
  - package
  - automation
  - publish
  - tools

screenshots:
  - description: 'Flutter Create'
    path: 'assets/images/flutter_create.gif'
