name: Build GUI Release

on:
  push:
    tags:
      - 'assist-v*'

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/gui

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install Linux GUI dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libsecret-1-dev \
            libjsoncpp-dev \
            libcurl4-openssl-dev

      - name: Build Flutter app (Linux)
        run: |
          flutter pub get
          flutter build linux

      - name: Archive bundle
        run: |
          mkdir -p dist
          tar -czf dist/assist_gui-linux-${{ github.ref_name }}.tar.gz -C build/linux/x64/release/bundle .

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/gui/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

#############################################################

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: packages/gui

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Build Flutter app (Windows)
        run: |
          flutter pub get
          flutter build windows

      - name: Archive build output
        run: |
          mkdir dist
          ls build/windows/x64/runner/Release
          7z a dist/assist_gui-windows-${{ github.ref_name }}.zip ./build/windows/x64/runner/Release/*

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/gui/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

#############################################################

  build-macos:
    name: Build (macOS)
    runs-on: macos-latest
    defaults:
      run:
        working-directory: packages/gui

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Build Flutter app (macOS)
        run: |
          flutter pub get
          flutter build macos

      - name: Archive app bundle
        shell: bash
        run: |
          mkdir -p dist
          app_bundle=$(find build/macos/Build/Products/Release -name "*.app" | head -n 1)
          ditto -c -k --sequesterRsrc --keepParent "$app_bundle" dist/assist_gui-macos-${{ github.ref_name }}.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: packages/gui/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}